### PR TITLE
Replaced sorted queue with priority queue.

### PR DESCRIPTION
**Pull request by Levalicious**
I've noticed a 40x improvement in performance on Brave v1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit.

### CODE REVIEW

**Comment by Levalicious** [comment]
With this concat optimization, it seems to actually be bound by the parser classification system, which I have no clue how to try to optimize. However, this seems to be another ~40x improvement on my computer.

**Comment by mdaines** [comment]
Seems plausible :-) I'll take a closer look this weekend. Where does priorityqueue.js come from?

**Comment by Levalicious** [comment]
It's a small port I made of a C minheap implementation that I use occasionally.

**Comment by Levalicious** [comment]
The optimization I tried broke the sentence generation and I hadn't noticed. At some point I might try replacing it with a button that generates a certain number of random sentences, so that it's decoupled from grammar processing & hopefully to optimize it a bit again.

**Comment by mdaines** [comment]
The min heap helps speed things up, but I think the calculation may need a limit on the size of the queue, or some other way to generate example sentences.

For me, this smaller grammar takes almost 4 seconds to analyze and most of the time is spent in the example sentences calculation:

```
a1 -> x .
a1 -> a2 x a2 .
a2 -> a3 x a3 .
a3 -> a1 x a1 .
```

**Comment by Levalicious** [comment]
Yep, I have some ideas for generating example sentences differently, but I haven't had a chance to tinker with any of them yet. Hopefully I'll get a chance to tinker with it some more over the next few days.

**Comment by mdaines** [comment]
I've just added a check to limit the depth of the queue: fadd52228273fb53e3472ee0e7ecfd2ed34f1dd0

That seems to address the performance issue with sentence generation. I'm going to leave this open for now to remind myself to implement the heap data structure at some point.

**Comment by mdaines** [comment]
Thank you for the suggestions and pull request. I'm planning to make some other changes to the example sentences calculation that would conflict with the changes, so I'm closing it.

**Pull request closed without merging**
